mov: mov.o
	ld -g mov.o -o mov
mov.o: mov.s
	as -g mov.s -o mov.o
addtwo: addtwo.o
	ld -g addtwo.o -o addtwo
addtwo.o: addtwo.s
	as -g addtwo.s -o addtwo.o
addten: addten.o
	ld -g addten.o -o addten
addten.o: addten.s
	as -g addten.s -o addten.o
